export const ACTION_SET_STORIES = 'ACTION_SET_STORIES';
export const ACTION_INIT_TEASERS = 'ACTION_INIT_TEASERS';
export const ACTION_UPDATE_TEASERS = 'ACTION_UPDATE_TEASERS';
export const ACTION_FAILED_TO_INIT = 'ACTION_FAILED_TO_INIT';



