export const ACTION_SET_STORIES = 'ACTION_SET_STORIES';
export const ACTION_FAILED_TO_INIT = 'ACTION_FAILED_TO_INIT';
export const ACTION_INIT_SET_LOADING = 'ACTION_INIT_SET_LOADING';
export const ACTION_SET_STORY_DATA = 'ACTION_SET_STORY_DATA';
export const ACTION_CURRENT_STORY = 'ACTION_CURRENT_STORY'



